apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to shared base
resources:
  - ../../base

# Optional: Apply name prefix/suffix
nameSuffix: -stage

namePrefix: app1-

labels:
  - pairs:
      env: stage
    includeSelectors: true # if we set it to false then it will only be applied to deployment not on th selector inside the deployment

images:
- name: nginx # Will look for container with image name nginx
  newName: nginx
  newTag: "1.22"

commonAnnotations:
  branch: stage
  support: 800-800

namespace: stage

replicas:
- name: nginx-deploy
  count: 3