apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

# Reference to shared base
resources:
  - ../../base

# Optional: Apply name prefix/suffix
nameSuffix: -dev
namePrefix: app1-

# Add common labels and annotations
labels:
  - pairs:
      env: dev
    includeSelectors: true

commonAnnotations:
  branch: dev
  support: 800-800

# Override container image
images:
  - name: nginx
    newName: nginx
    newTag: "latest"

# Target namespace
namespace: dev

# Scale to 2 replicas
replicas:
  - name: nginx-deploy
    count: 2


patches:
  # Decide the target it can be deployment / service / daemonset etc
  # patch for deployment
  - target:
      group: apps
      version: v1
      kind: Deployment
      name: nginx-deploy
    # there are two types of patch styles ie 1. json patch 2. merge patch style
    # in json type we specify the operation, path and the json yaml
    # in merge style patch we write the partial target yaml
    patch: |-
      - op: add 
        path: /spec/template/spec/containers/0/env
        value:  
          - name: LOG_LEVEL
            value: debug
      - op: replace
        path: /spec/template/spec/containers/0/resources
        value:
          requests:
            cpu: "100m"
            memory: "128Mi"
          limits:
            cpu: "500m"
            memory: "256Mi"
      - op: remove
        path: /metadata/labels/unused 
         